# Valores duplicados

In [1]:
import numpy as np
import pandas as pd
DF= pd.DataFrame({'col 1':[1,1,2,2,3,3,3],
                  'col 2': ['a','a','b','b','c','c','c'],
                  'col3 ': ['A','A','B','B','C','C','C']})
DF

   col 1 col 2 col3
0      1     a     A
1      1     a     A
2      2     b     B
3      2     b     B
4      3     c     C
5      3     c     C
6      3     c     C

In [2]:
DF.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [3]:
DF.drop_duplicates()

   col 1 col 2 col3
0      1     a     A
2      2     b     B
4      3     c     C

In [4]:
DF= pd.DataFrame({'col 1':[1,1,2,2,3,3,3],
                  'col 2': ['a','a','b','b','c','c','c'],
                  'col3 ': ['A','A','B','B','C','C','C']})
DF

   col 1 col 2 col3
0      1     a     A
1      1     a     A
2      2     b     B
3      2     b     B
4      3     c     C
5      3     c     C
6      3     c     C

In [5]:
DF.drop_duplicates(['col 1'])

   col 1 col 2 col3
0      1     a     A
2      2     b     B
4      3     c     C

# Crear serie multiindex

In [6]:
arrays = [np.array(["a", "a", "a", "b", "b", "b", "c", "c","c"]),
          np.array([1,2,3, 1,2,3, 1,2,3]),]
s = pd.Series(np.random.randn(9), index=arrays)
print(s)

a  1   -1.071108
   2   -1.843875
   3    0.894571
b  1   -0.368005
   2    0.282579
   3    1.643882
c  1    1.289166
   2   -0.472169
   3   -0.432274
dtype: float64

In [7]:
s.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('c', 3)],
           )

In [8]:
# Primero nivel
s['a']

1   -1.071108
2   -1.843875
3    0.894571
dtype: float64

In [9]:
# Segundo nivel
s.loc[:,2]

a   -1.843875
b    0.282579
c   -0.472169
dtype: float64

In [10]:
s.unstack()

          1         2         3
a -1.071108 -1.843875  0.894571
b -0.368005  0.282579  1.643882
c  1.289166 -0.472169 -0.432274

In [11]:
s.sum(level=1)

<ipython-input-11-f9ea8fa8b215>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  s.sum(level=1)

1   -0.149947
2   -2.033465
3    2.106179
dtype: float64

In [12]:
s.sum(level=0)

<ipython-input-12-f29a8ec3f800>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  s.sum(level=0)

a   -2.020412
b    1.558456
c    0.384723
dtype: float64

In [13]:
s.mean(level=0)

<ipython-input-13-0ca14a3b5a04>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  s.mean(level=0)

a   -0.673471
b    0.519485
c    0.128241
dtype: float64

# Ejemplos print

In [14]:
print('Pero', 'no', 'incluyendo', sep='**')

Pero**no**incluyendo

In [15]:
print('Pero', 'no', 'incluyendo', sep='')

Peronoincluyendo

In [16]:
print('hola\n')

hola

In [17]:
print('hola\n', end='')

hola

# Group by

In [18]:
df = pd.DataFrame({'data1' : np.random.randn(5), 
                   'data2' : np.random.randn(5),
                   'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one']})
df

      data1     data2 key1 key2
0  0.626800 -1.554636    a  one
1 -0.932949 -0.109220    a  two
2  0.069181  0.758314    b  one
3 -0.398211 -2.258394    b  two
4 -1.519480 -0.725122    a  one

In [19]:
grouped=df['data1'].groupby(df['key1'])
type(grouped)

pandas.core.groupby.generic.SeriesGroupBy

In [20]:
grouped.median()

key1
a   -0.932949
b   -0.164515
Name: data1, dtype: float64

In [21]:
df['data1'].groupby(df['key1']).sum()

key1
a   -1.825629
b   -0.329030
Name: data1, dtype: float64

In [22]:
df['data1'].groupby([df['key1'],df['key2']]).sum()

key1  key2
a     one    -0.892680
      two    -0.932949
b     one     0.069181
      two    -0.398211
Name: data1, dtype: float64

In [23]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
'key2' : ['one', 'two', 'one', 'two', 'one'],
'data1' : np.random.randn(5),
'data2' : np.random.randn(5)})

# Pivot

In [24]:
df = pd.DataFrame(data={'A' : ['John', 'Boby', 'Mina'],
'B' : ['Masters', 'Graduate', 'Graduate'],
'C' : [27,23,21]})
df

      A         B   C
0  John   Masters  27
1  Boby  Graduate  23
2  Mina  Graduate  21

In [25]:
df.pivot(index='A',columns='B')

            C
B    Graduate Masters
A
Boby     23.0     NaN
John      NaN    27.0
Mina     21.0     NaN

In [26]:
df.pivot(index='B',columns='C')

             A
C           21    23    27
B
Graduate  Mina  Boby   NaN
Masters    NaN   NaN  John

In [27]:
df.pivot('A','C')

             B
C           21        23       27
A
Boby       NaN  Graduate      NaN
John       NaN       NaN  Masters
Mina  Graduate       NaN      NaN

In [28]:
df.pivot('A','B','C')

B     Graduate  Masters
A
Boby      23.0      NaN
John       NaN     27.0
Mina      21.0      NaN

In [29]:
df.pivot(index='A',columns='B',values=['C'])

            C
B    Graduate Masters
A
Boby     23.0     NaN
John      NaN    27.0
Mina     21.0     NaN

In [30]:
# Porque hay error aca
df1 = pd.DataFrame({'A' : ['John', 'John', 'Mina'],
'B' : ['Masters', 'Masters', 'Graduate'],
'C' : [27,23,21]})
df1.pivot(index='A',columns='B',values=['C'])

ValueError: ignored

# Apply

In [31]:
df = pd.DataFrame({'A' : [1,2,3,4],
'B' : [5,6,7,8],
'C' : [9,10,11,12],
'D' : [13,14,15,16]})
df

   A  B   C   D
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16

In [32]:
df1= df.copy()
df1

   A  B   C   D
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16

In [33]:
df1.apply(np.sqrt)

          A         B         C         D
0  1.000000  2.236068  3.000000  3.605551
1  1.414214  2.449490  3.162278  3.741657
2  1.732051  2.645751  3.316625  3.872983
3  2.000000  2.828427  3.464102  4.000000

In [34]:
# Creo mi funcion
def cubo_david(y):
  return y**3

df['A'].apply(cubo_david)

0     1
1     8
2    27
3    64
Name: A, dtype: int64

# Value_counts

In [35]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
'key2' : ['one', 'two', 'one', 'two', 'one'],
'data1' : np.random.randn(5),
'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.090541  0.064401
1    a  two -0.403807 -0.655321
2    b  one -0.107309  0.852931
3    b  two -1.079526  1.082420
4    a  one -0.641448  1.271256

In [36]:
df.key2.value_counts()

one    3
two    2
Name: key2, dtype: int64

# Sorting index and values

In [37]:
df = pd.DataFrame({'A' : [1,2,8,3,5]})
df.index=[100,29,234,1,150]
df

     A
100  1
29   2
234  8
1    3
150  5

In [38]:
df.sort_index(ascending=False)

     A
234  8
150  5
100  1
29   2
1    3

In [39]:
df.sort_values('A',ascending=False)

     A
234  8
150  5
1    3
29   2
100  1

# Melt

## Parte 1

In [40]:
import pandas as pd
df = pd.DataFrame({'P': {0: 'p', 1: 'q', 2: 'r'},
                   'Q': {0: 2, 1: 4, 2: 6},
                   'R': {0: 3, 1: 5, 2: 7}})
df

   P  Q  R
0  p  2  3
1  q  4  5
2  r  6  7

In [41]:
pd.melt(df, id_vars=['P'], value_vars=['Q'])

   P variable  value
0  p        Q      2
1  q        Q      4
2  r        Q      6

In [42]:
pd.melt(df, id_vars=['P'], value_vars=['Q', 'R'])

   P variable  value
0  p        Q      2
1  q        Q      4
2  r        Q      6
3  p        R      3
4  q        R      5
5  r        R      7

Podemos customizar los nombres de las columnas

In [43]:
pd.melt(df, id_vars=['P'], value_vars=['Q'],
        var_name='Nombre_Variable', value_name='Nombre_valor')

   P Nombre_Variable  Nombre_valor
0  p               Q             2
1  q               Q             4
2  r               Q             6

En el caso que tengan multiindex por ejemplo

In [44]:
df.columns = [list('PQR'), list('STU')]
df

   P  Q  R
   S  T  U
0  p  2  3
1  q  4  5
2  r  6  7

In [45]:
pd.melt(df, col_level=0, id_vars=['P'], value_vars=['Q'])

   P variable  value
0  p        Q      2
1  q        Q      4
2  r        Q      6

In [46]:
pd.melt(df, col_level=1, id_vars=['S'], value_vars=['Q'])

   S variable  value
0  p        U      3
1  q        U      5
2  r        U      7

In [47]:
pd.melt(df, id_vars=[('P', 'S')], value_vars=[('Q', 'T')])

  (P, S) variable_0 variable_1  value
0      p          Q          T      2
1      q          Q          T      4
2      r          Q          T      6

## Parte 2

In [48]:
df = pd.DataFrame({'Name': {0: 'John', 1: 'Bob', 2: 'Shiela'},
                   'Course': {0: 'Masters', 1: 'Graduate', 2: 'Graduate'},
                   'Age': {0: 27, 1: 23, 2: 21}})
df

     Name    Course  Age
0    John   Masters   27
1     Bob  Graduate   23
2  Shiela  Graduate   21

In [49]:
pd.melt(df, id_vars =['Name'], value_vars =['Course'])

     Name variable     value
0    John   Course   Masters
1     Bob   Course  Graduate
2  Shiela   Course  Graduate

In [50]:
# multiple unpivot columns
pd.melt(df, id_vars =['Name'], value_vars =['Course', 'Age'])

     Name variable     value
0    John   Course   Masters
1     Bob   Course  Graduate
2  Shiela   Course  Graduate
3    John      Age        27
4     Bob      Age        23
5  Shiela      Age        21

# Desafio

In [51]:
from google.colab import drive
import os
drive.mount('/content/gdrive')
# Establecer ruta de acceso en drive
import os
print(os.getcwd())
os.chdir("/content/gdrive/My Drive")

Mounted at /content/gdrive
/content

In [52]:
datos=pd.read_csv('datos_empresas.csv')
datos

    Id    Nombre  Ventas
0    1    Quasco    1500
1    2    Tutiro    1300
2    3     Tyuan    1900
3    4   Quantum    1200
4    5  Bertlitz    1400
5    6     Ascor    1700
6    7   Trition    1670
7    8     Teryu    1345
8    9     Oyude    1564
9   10     Yende    1567
10  11    Attron    1346
11  12      Atom    1567
12  13    Quasco    1764
13  14      Tigo    1865
14  15     Claro    1953
15  16  Movistar    1756
16  17    Spirit    1346
17  18        Ut    1654
18  19    Porter    1675
19  20     Tuyer    1457
20  21  Upstream    1324
21  22     It-es    1876
22  23  Daniela     1546
23  24       SAO    1453
24  25     Jumbo    1656
25  26  Olimpica    1456
26  27  Olimpia     1345
27  28    Nartel    1276
28  29      Yuor    1876
29  30    JT-Log    1912

In [53]:
datos.sort_values(by='Ventas',ascending=False)

    Id    Nombre  Ventas
14  15     Claro    1953
29  30    JT-Log    1912
2    3     Tyuan    1900
28  29      Yuor    1876
21  22     It-es    1876
13  14      Tigo    1865
12  13    Quasco    1764
15  16  Movistar    1756
5    6     Ascor    1700
18  19    Porter    1675
6    7   Trition    1670
24  25     Jumbo    1656
17  18        Ut    1654
11  12      Atom    1567
9   10     Yende    1567
8    9     Oyude    1564
22  23  Daniela     1546
0    1    Quasco    1500
19  20     Tuyer    1457
25  26  Olimpica    1456
23  24       SAO    1453
4    5  Bertlitz    1400
16  17    Spirit    1346
10  11    Attron    1346
7    8     Teryu    1345
26  27  Olimpia     1345
20  21  Upstream    1324
1    2    Tutiro    1300
27  28    Nartel    1276
3    4   Quantum    1200

In [54]:
datos.drop_duplicates(subset='Nombre')

    Id    Nombre  Ventas
0    1    Quasco    1500
1    2    Tutiro    1300
2    3     Tyuan    1900
3    4   Quantum    1200
4    5  Bertlitz    1400
5    6     Ascor    1700
6    7   Trition    1670
7    8     Teryu    1345
8    9     Oyude    1564
9   10     Yende    1567
10  11    Attron    1346
11  12      Atom    1567
13  14      Tigo    1865
14  15     Claro    1953
15  16  Movistar    1756
16  17    Spirit    1346
17  18        Ut    1654
18  19    Porter    1675
19  20     Tuyer    1457
20  21  Upstream    1324
21  22     It-es    1876
22  23  Daniela     1546
23  24       SAO    1453
24  25     Jumbo    1656
25  26  Olimpica    1456
26  27  Olimpia     1345
27  28    Nartel    1276
28  29      Yuor    1876
29  30    JT-Log    1912